### ISSUE TITLE
Pod Issue - JNWScrollView.h file not found

### ISSUE THREAD

**Issue by KCastiglione** [jwilling/JNWCollectionView#139]
I am trying to integrate JNWCollectionView into my Pods.

Added to Podfile

     pod 'JNWCollectionView'

Did pod install

     pod install
     Analyzing dependencies
     Downloading dependencies
     Installing AFNetworking (2.5.3)
     Installing JNWCollectionView (1.3)
     Installing JNWScrollView (0.1)
     Generating Pods project
     Integrating client project

On opening the xcworkspace, compiling fails saying 'JNWScrollView.h file not found', and on checking Pods, JNWScrollView folder is empty. Screenshot below:

![screen shot 2015-05-03 at 12 52 50 pm](https://cloud.githubusercontent.com/assets/96905/7446618/651a917e-f193-11e4-81a6-ce5aac507713.png)

**Comment by jwilling** [comment]
I just tested this locally and there were no problems pulling down the `JNWScrollView` dependency. What version of CocoaPods are you running? Are you sure you have the workspace open and not the project itself?

**Comment by KCastiglione** [comment]
I tried again, the problem still exists.
Let me know if I should try a different version of pod or JNWCollectionView
Xcode - Version 6.3.1 (6D1002)

      $ pod --version
      0.37.0

added JNWCollectionview to Podfile
      $ cat Podfile
      platform :osx, '10.8'
      pod 'AFNetworking', '~> 2.5.3'
      pod 'STTwitter'
      pod 'JNWCollectionView'


      pod install
      Analyzing dependencies
      Removing JNWLabel
      Downloading dependencies
      Using AFNetworking (2.5.3)
      Installing JNWCollectionView (1.3)
      Installing JNWScrollView (0.1)
      Using STTwitter (0.2.0)
      Generating Pods project
      Integrating client project

      $ open mac.xcworkspace


![screen shot 2015-05-04 at 11 17 39 am](https://cloud.githubusercontent.com/assets/96905/7459210/33896a92-f24f-11e4-9f49-c878d07f5d0c.png)




![screen shot 2015-05-04 at 11 18 01 am](https://cloud.githubusercontent.com/assets/96905/7459220/3f29065a-f24f-11e4-9bb6-16b313ad02b6.png)

**Comment by jwilling** [comment]
Frankly I don't know what's going on. Seems like an issue with CocoaPods, not my library. I tried your Podfile in a test project and it pulled everything correctly. Hate to ask this, but have you restarted Xcode? Can you delete your pods folder and Podfile.lock file and try installing it again?

**Comment by KCastiglione** [comment]
Thanks for following up.

Yes I have restarted Xcode, deleted Pods folder, Podlock, tried with fresh project, and several combinations of the same.

Can you tell which version of pod and Xcode you are using? Thanks again!

**Comment by jwilling** [comment]
I'm using Xcode 6.3.1, but that shouldn't make a difference, should it? The same Podfile has worked all the way back to Xcode 6.0, if I recall correctly.

**Comment by jwilling** [comment]
I'll admit I really don't know too much about CocoaPods so frankly I'm not sure how to solve the problem.

**Comment by KCastiglione** [comment]
Can you please give the output, So I can try with same pod version as yours

     pod --version

**Comment by jwilling** [comment]
0.37.0

**Comment by mrniket** [comment]
In line 24 at `JNWCollectionViewFramework.h` I replaced the line:

    #import "JNWScrollView.h"

with 

    #import "JNWScrollView/JNWScrollView.h"

That got rid of the problem for me

**Comment by jwilling** [comment]
@mrniket So you were having problems as well? That's odd. Thanks for sharing that info.

**Comment by KCastiglione** [comment]
@jwilling This finally is fixed with latest gem.

It did not even require the change that @mrniket had to do.
Thanks for all the help

**Comment by CWalig** [comment]
I had to do the same as @mrniket  - pod version 0.38.2

Just to let you know ;)

**Comment by jwilling** [comment]
Quite odd. I just made a sample app again using CocoaPods version 0.38.2, and it had no problem building. I'm not sure how my configuration is different from y'alls, but something must not be the same.

**Comment by CWalig** [comment]
Here is a sample project http://d.pr/f/183Wk
I usually create a framework with all my API calls (BoxDataKit in the project). 
There is no target inside the PodFile otherwise I get some issues.

I might be missing something, let me know.

**Comment by jwilling** [comment]
Thanks for the sample. I'm still not quite sure why it's happening, but I'll restructure the project to ensure it builds both for CocoaPods and for regular framework installs.

Due to certain restrictions at my current job I'm unable to push new code until later in August, so it will be some time before I can make the fix. In the meantime, please use the workaround given by @mrniket. Sorry for the trouble!

**Comment by jeffleeismyhero** [comment]
With a fresh clone of this repo, I get this same error when trying to build the Demo application. Changing `#import "JNWScrollView.h"` to `#import "JNWScrollView/JNWScrollView.h"` does not resolve the issue.

**Comment by jwilling** [comment]
@jeffleeismyhero Yes indeed, the dependencies are needed. I did note that near the bottom of the readme, but perhaps it could use more visibility. Sorry for the trouble.

**Comment by jeffleeismyhero** [comment]
@jwilling Thanks. It took me a while to find that info. In fact, I didn't see it until after I resolved the issue. Maybe it would be good to have that information in an "Cloning the Repo / Install" or "Running the Demo" section?

Either way, thanks for the great code!

**Comment by jwilling** [comment]
I've pushed some changes to dependencies. A quick test with making a project seems to work. Let me know if issues still occur.

**Comment by CWalig** [comment]
Dang the issue is back!

My podfile
```
target 'MyProject' do
    pod 'JNWCollectionView', '~> 1.4', :inhibit_warnings => true
end
```

In `JNWCollectionViewFramework.h`
![screen shot 2016-07-06 at 8 03 12 pm](https://cloud.githubusercontent.com/assets/2945380/16611337/c5b2476a-43b4-11e6-9f54-2279f0325ea1.png)

Any idea?

Thanks!

**Comment by jwilling** [comment]
I just tried a new project using CocoaPods version 1.0.1, and it worked just fine. Did you recently change a configuration or anything without cleaning your build?
